### ISSUE TITLE
[BUG] The client response body can only be consumed once

### ISSUE THREAD

**Issue by wls981** [apache/incubator-shenyu#3165] opened 2022-04-01 07:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/15735480/161216071-1b7e888b-72f2-4e12-b1f7-727b6ea7e773.png)

I am using shenyu2.4.2 for stress testing, when the concurrency exceeds 4, the exception shown in the figure above will be thrown. Changed to shenyu2.4.1 for the same test, and no exception occurred.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/15735480/161217240-14d0e95b-5c07-46f7-8254-f091d89695a8.png)

1、Using apache-shenyu-incubating-2.4.2-bootstrap-bin.tar.gz；
2、A very simple backend http application that returns 10 characters directly. As shown in above FIG.
3、Using apachebench(ab): ab -n 20000 -c 16 http://localhost:8080/aaa

### Environment

```markdown
ShenYu version(s):2.4.2
```

**Comment by qicz** [comment] 2022-04-01 08:19
@wls981 maybe try the last version at the master branch.  we used the shenyu for a long time,  this problem does not exist.

**Comment by qicz** [comment] 2022-04-02 02:01
I close this issue, you can try the last version. if this `bug` is present again,  tell me and refer issue again.    @wls981

**Closed by qicz** 2022-04-02 02:01 UTC
Labels: type: bug

**Comment by jjxliu306** [comment] 2022-05-16 02:11
在压力测试下，基本会一直重现这个异常：
Caused by: java.lang.IllegalStateException: The client response body can only be consumed once.
	at org.springframework.http.client.reactive.ReactorClientHttpResponse.lambda$getBody$0(ReactorClientHttpResponse.java:66)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

请问都是怎么处理的。
