### ISSUE TITLE
how to get requset body in my plugin??

### ISSUE THREAD

**Issue by iwongta** [apache/incubator-shenyu#1747] opened 2021-07-11 05:52 UTC
## Question

// your question here;

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by KevinClair** [comment] 2021-07-11 07:04
Please see here #1684

**Comment by dengliming** [comment] 2021-07-11 14:11
Duplicate of [https://github.com/apache/incubator-shenyu/issues/1684](https://github.com/apache/incubator-shenyu/issues/1684)

**Closed by dengliming** 2021-07-11 14:11 UTC
Labels: type: duplicate, type: question

**Comment by iwongta** [comment] 2021-07-13 00:58
exchange.getRequest().getBody()
        .map(x -> {
          byte[] b = new byte[x.readableByteCount()];
          x.read(b);
          String string = new String(b , StandardCharsets.UTF_8);
          exchange.getAttributes().put(Constants.PARAM_TRANSFORM , string);
          log.info("PreFcOpenPlugin Constants.PARAM_TRANSFORM => {}" , string);
          return string;
        }).subscribe();
        此方式获取，频繁出现  Connection prematurely closed BEFORE response
