### ISSUE TITLE
Http request on GET method with encoded json

### ISSUE THREAD

**Issue by verysimple44** [apache/incubator-shenyu#1785] opened 2021-07-16 08:24 UTC
## Describe the bug
request uri like this
http://localhost:9195/project/path/test?name=%5B%7B%22a%22:%20%22b%22%7D%5D
or
http://localhost:9195/project/path/test/%E6%B5%8B%E8%AF%95

it will be as below when decoded
http://localhost:9195/project/path/test?name=[{"a": "b"}]
or
http://localhost:9195/project/path/test/[{"a": "b"}]

but gateway use getPath&getQuery instead of getRawPath&getRawQuery
when process in ”webClient.method(method).uri(urlPath)”, the character '{' is identified as a placeholder start, just like
http://xxx/{value1}/{value2}?value={value3}, so gateway throw a no more value exception

**This kind request is do exist on "MeiTuan" callback.**

## Environment

- ShenYu version(s): master

## Expected behavior
1. Use getRawPath&getRawQuery replace of getPath&getQuery
2. Set the 'EncodingMode.VALUES_ONLY' to webClient, so that uri method will never encode our uri again

## Debug logs

<details>

</details>

**Comment by yu199195** [comment] 2021-07-16 08:31
we will fix

**Comment by KevinClair** [comment] 2021-07-16 11:19
Duplicate of #1778

**Closed** 2021-07-16 11:19 UTC
Labels: type: bug
