### ISSUE TITLE
哪里有 shenyu admin模块的前段 源码

### ISSUE THREAD

**Issue by wangfl-13923768399** [apache/incubator-shenyu#1637] opened 2021-06-18 09:41 UTC
## Question

// your question here;

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by dengliming** [comment] 2021-06-18 09:46
Duplicate of [https://github.com/apache/incubator-shenyu/issues/1638](https://github.com/apache/incubator-shenyu/issues/1638)

**Closed by dengliming** 2021-06-18 09:46 UTC
Labels: type: question
