### ISSUE TITLE
配置文件中没有iv配置属性，导致登录报错

### ISSUE THREAD

**Issue by qinliang373** [apache/incubator-shenyu#1752] opened 2021-07-11 13:57 UTC
## Describe the bug
Caused by: java.lang.NullPointerException: null
	at org.apache.shenyu.admin.utils.CipherUtils.cipherTool(CipherUtils.java:56)
	at org.apache.shenyu.admin.utils.CipherUtils.lambda$encryptHex$0(CipherUtils.java:78)
7月11号更新到最新代码登录报错，定位发现iv配置属性中没有值注入
aes:
    secret:
      key: 2095132720951327

## Environment

- ShenYu version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment] 2021-07-11 14:09
Duplicate of [https://github.com/apache/incubator-shenyu/issues/1749](https://github.com/apache/incubator-shenyu/issues/1749)

**Closed by dengliming** 2021-07-11 14:09 UTC
Labels: type: bug, type: duplicate
