### ISSUE TITLE
[BUG] <If you use nacos data synchronization, the registration fails and the registration is still successful>

### ISSUE THREAD

**Issue by gaochuang98** [apache/incubator-shenyu#2783] opened 2022-01-17 10:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you use nacos data synchronization, the registration fails and the registration is still successful

### Expected Behavior

I want to modify other registry logs
Make it as elegant to use as
`HttpClientRegisterRepository`

### Steps To Reproduce

look #issue 2710

### Environment

```markdown
ShenYu version(s):master
```

**Comment by gaochuang98** [comment] 2022-01-17 10:53
please assign it to me

**Comment by KevinClair** [comment] 2022-01-17 10:58
Duplicate of #2710

**Closed** 2022-01-21 10:54 UTC
Labels: type: bug, data-sync: nacos
