### ISSUE TITLE
I have a problem with sofa.  Please help me to have a look

### ISSUE THREAD

**Issue by Summary-wcj** [apache/incubator-shenyu#3461] opened 2022-05-31 08:02 UTC
### Question

I used the local startup method to test the interface of sofa. The following errors occurred. The registry used was zookeeper and the example provided on the official website was used

Error log printed by the gateway when called

`2022-05-31 15:34:38 [boundedElastic-3] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sofa selector success match , selector name :/sofa
2022-05-31 15:34:38 [boundedElastic-3] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sofa rule success match , rule name :/sofa/findAll
2022-05-31 15:34:38 [boundedElastic-3] ERROR org.apache.shenyu.web.handler.GlobalErrorHandler - [b54a2486] Resolved [SofaRouteException: RPC-020060001: 没有获得服务[org.apache.shenyu.examples.sofa.api.service.SofaSingleParamService:1.0]的调用地址，请检查服务是否已经推送 ] for HTTP GET /sofa/findAll
`
Information on zookeeper
![image](https://user-images.githubusercontent.com/34983781/171123715-3b796a0e-b07a-4ca2-8cce-3cb8e3a128d6.png)

**Comment by Summary-wcj** [comment] 2022-06-01 03:02
> I'll have a look.

thank you

**Comment by moremind** [comment] 2022-06-01 03:04
please tell me your shenyu version,zookeeper version and detail log.

**Comment by Summary-wcj** [comment] 2022-06-01 05:46
> please tell me your shenyu version,zookeeper version and detail log.

master branch

**Comment by li-keguo** [comment] 2022-06-01 07:28
I also encountered the same situation, zk version tested 3.7 and 3.8

**Comment by Summary-wcj** [comment] 2022-06-01 07:46
> I also encountered the same situation, zk version tested 3.7 and 3.8
> 
> in https://github.com/sofastack/sofa-rpc/blob/ddccf7aef5d2414dc51274a5b76e3c0c2df161db/core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
> 
> I find code:
> 
> ```java
>         if (CommonUtils.isEmpty(providerInfos)) {
>             /**
>              * 如果注册中心没有provider，可能上下文中指定了provider
>              *
>              * 注册中心如果没有provider可用列表，需要识别上下文中是否存在直连Provider:
>              * 1. RpcInvokeContext.getContext().getTargetUrl()
>              */
>             if (context != null) {
>                 String targetIP = (String) context.getAttachment(RpcConstants.HIDDEN_KEY_PINPOINT);
>                 if (StringUtils.isNotBlank(targetIP)) {
>                     // 如果上下文指定provider，直接返回
>                     ProviderInfo providerInfo = selectPinpointProvider(targetIP, providerInfos);
>                     return providerInfo;
>                 }
>             }
> 
>             throw noAvailableProviderException(message.getTargetServiceUniqueName());
>         } else {
>             originalProviderInfos = new ArrayList<>(providerInfos);
>         }
> ```

Is this the source code of sofa? Did you meet it, too? What's a good way now

**Comment by li-keguo** [comment] 2022-06-01 09:24
> > I didn't solve it
> 
> This should be a bug

yes ! We are trying to fix it, if you are interested in this topic, please feel free to contribute~

**Comment by hgaol** [comment] 2022-06-01 10:57
I created a PR for this issue. Feel free to leave comment.

**Comment by hgaol** [comment] 2022-06-01 11:00
The root cause is curator version incompatible.

**Comment by Summary-wcj** [comment] 2022-06-02 01:08
> Have you tried adding below dependencies in `bootstrap`?
> 
> ```
> <dependency>
>                <groupId>org.apache.curator</groupId>
>                <artifactId>curator-client</artifactId>
>                <version>4.0.1</version>
>            </dependency>
>            <dependency>
>                <groupId>org.apache.curator</groupId>
>                <artifactId>curator-framework</artifactId>
>                <version>4.0.1</version>
>            </dependency>
>            <dependency>
>                <groupId>org.apache.curator</groupId>
>                <artifactId>curator-recipes</artifactId>
>                <version>4.0.1</version>
>            </dependency>
> ```

In version 2.4.3, there is this version of curator. I have tried it without any problem.  but I have not tried it on the master branch

**Comment by hgaol** [comment] 2022-06-02 01:38
> > Have you tried adding below dependencies in `bootstrap`?
> > ```
> > <dependency>
> >                <groupId>org.apache.curator</groupId>
> >                <artifactId>curator-client</artifactId>
> >                <version>4.0.1</version>
> >            </dependency>
> >            <dependency>
> >                <groupId>org.apache.curator</groupId>
> >                <artifactId>curator-framework</artifactId>
> >                <version>4.0.1</version>
> >            </dependency>
> >            <dependency>
> >                <groupId>org.apache.curator</groupId>
> >                <artifactId>curator-recipes</artifactId>
> >                <version>4.0.1</version>
> >            </dependency>
> > ```
> 
> In version 2.4.3, there is this version of curator. I have tried it without any problem. but I have not tried it on the master branch

You can pull the newest master branch and test again, it should be fixed. But pay attention, please don't use zk as data sync. I'll fix it in future PR.

**Comment by Summary-wcj** [comment] 2022-06-02 02:23
> > > Have you tried adding below dependencies in `bootstrap`?
> > > ```
> > > <dependency>
> > >                <groupId>org.apache.curator</groupId>
> > >                <artifactId>curator-client</artifactId>
> > >                <version>4.0.1</version>
> > >            </dependency>
> > >            <dependency>
> > >                <groupId>org.apache.curator</groupId>
> > >                <artifactId>curator-framework</artifactId>
> > >                <version>4.0.1</version>
> > >            </dependency>
> > >            <dependency>
> > >                <groupId>org.apache.curator</groupId>
> > >                <artifactId>curator-recipes</artifactId>
> > >                <version>4.0.1</version>
> > >            </dependency>
> > > ```
> > 
> > 
> > In version 2.4.3, there is this version of curator. I have tried it without any problem. but I have not tried it on the master branch
> 
> You can pull the newest master branch and test again, it should be fixed. But pay attention, please don't use zk as data sync. I'll fix it in future PR.

Well thank you.

**Comment by Summary-wcj** [comment] 2022-06-02 07:20
> > > > Have you tried adding below dependencies in `bootstrap`?
> > > > ```
> > > > <dependency>
> > > >                <groupId>org.apache.curator</groupId>
> > > >                <artifactId>curator-client</artifactId>
> > > >                <version>4.0.1</version>
> > > >            </dependency>
> > > >            <dependency>
> > > >                <groupId>org.apache.curator</groupId>
> > > >                <artifactId>curator-framework</artifactId>
> > > >                <version>4.0.1</version>
> > > >            </dependency>
> > > >            <dependency>
> > > >                <groupId>org.apache.curator</groupId>
> > > >                <artifactId>curator-recipes</artifactId>
> > > >                <version>4.0.1</version>
> > > >            </dependency>
> > > > ```
> > > 
> > > 
> > > In version 2.4.3, there is this version of curator. I have tried it without any problem. but I have not tried it on the master branch
> > 
> > 
> > You can pull the newest master branch and test again, it should be fixed. But pay attention, please don't use zk as data sync. I'll fix it in future PR.
> 
> Well thank you.

Hello, which version of ZK synchronization data is available

**Comment by hgaol** [comment] 2022-06-02 12:51
Hi @Summary-wcj , the PR which fix the zk data sync issue has been merged. Now you can pull the master branch and use zk data sync~
The versions of supported ZK should be >= 3.5.

**Comment by Summary-wcj** [comment] 2022-06-05 05:50
> 你好@Summary-wcj，修复 zk 数据同步问题的 PR 已合并。现在你可以拉取master分支并使用zk数据同步 了~ 支持的ZK版本应该>= 3.5。

Thank you very much. I have seen the updated records

**Closed** 2022-06-08 11:55 UTC
Labels: type: bug, type: question
