### ISSUE TITLE
[BUG] <Sentinel Plugin-exception ration and exception number is not effective>

### ISSUE THREAD

**Issue by moremind** [apache/incubator-shenyu#2720] opened 2022-01-06 08:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Configuration:
![image](https://user-images.githubusercontent.com/20184263/148351624-d89e14e3-24be-4d9d-9c55-f229e0776a95.png)

### Expected Behavior

use exception number strategy, count=5,can't arrived my service.

### Steps To Reproduce

first configuration: ![image](https://user-images.githubusercontent.com/20184263/148351624-d89e14e3-24be-4d9d-9c55-f229e0776a95.png)
second test:
![image](https://user-images.githubusercontent.com/20184263/148352139-b7f83693-9683-4892-93c6-f8bfcb78d595.png)

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Debug logs

2022-01-06 14:01:01 [shenyu-netty-nio-2] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sentinel selector success match , selector name :test1
2022-01-06 14:01:01 [shenyu-netty-nio-2] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sentinel rule success match , rule name :tset22
2022-01-06 14:01:01 [shenyu-netty-nio-2] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide selector success match , selector name :1111
2022-01-06 14:01:01 [shenyu-netty-nio-2] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide rule success match , rule name :test-http
2022-01-06 14:01:01 [shenyu-netty-nio-2] INFO  org.apache.shenyu.plugin.httpclient.WebClientPlugin - The request urlPath is http://10.10.2.59:8878/test/http/random, retryTimes is 3
2022-01-06 14:01:01 [shenyu-netty-nio-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sentinel selector success match , selector name :test1
2022-01-06 14:01:01 [shenyu-netty-nio-3] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sentinel selector success match , selector name :test1
2022-01-06 14:01:01 [shenyu-netty-nio-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sentinel rule success match , rule name :tset22
2022-01-06 14:01:01 [shenyu-netty-nio-3] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - sentinel rule success match , rule name :tset22
2022-01-06 14:01:01 [shenyu-netty-nio-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide selector success match , selector name :1111
2022-01-06 14:01:01 [shenyu-netty-nio-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide rule success match , rule name :test-http
2022-01-06 14:01:01 [shenyu-netty-nio-3] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide selector success match , selector name :1111

**Comment by yu199195** [comment] 2022-01-06 09:12
whats mean 。。？

**Comment by moremind** [comment] 2022-01-06 09:14
> whats mean 。。？

exception ration and exception number of sentinel plugin is `Not effective`

**Comment by moremind** [comment] 2022-01-07 02:59
![image](https://user-images.githubusercontent.com/20184263/148484281-cb45e334-2942-4841-9289-a20f4e9188eb.png)

I find this question,the result must execute doOnSuccess

**Comment by moremind** [comment] 2022-01-07 03:00
> ![image](https://user-images.githubusercontent.com/20184263/148484281-cb45e334-2942-4841-9289-a20f4e9188eb.png)
> 
> I find this question,the result must execute doOnSuccess

can't resolve the throwalbe

**Comment by moremind** [comment] 2022-01-07 08:01
I think exception number or exception ration isn't shenyu-gateway,may be a forwarded service.
![image](https://user-images.githubusercontent.com/20184263/148511601-42fd80f5-9290-435b-aa29-ac4e35134852.png)

**Comment by KevinClair** [comment] 2022-01-11 15:09
Duplicate of #2743

**Comment by moremind** [comment] 2022-01-12 09:52
> Duplicate of #2743

the author  of  #2743 is my friend,we try to fix it

**Closed** 2022-01-14 16:01 UTC
Labels: type: bug, plugin: sentinel
